/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterArtisanRouteImport } from './routes/register-artisan'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiAssistantRouteImport } from './routes/api/ai-assistant'

const RegisterArtisanRoute = RegisterArtisanRouteImport.update({
  id: '/register-artisan',
  path: '/register-artisan',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAssistantRoute = ApiAiAssistantRouteImport.update({
  id: '/api/ai-assistant',
  path: '/api/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register-artisan': typeof RegisterArtisanRoute
  '/api/ai-assistant': typeof ApiAiAssistantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register-artisan': typeof RegisterArtisanRoute
  '/api/ai-assistant': typeof ApiAiAssistantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register-artisan': typeof RegisterArtisanRoute
  '/api/ai-assistant': typeof ApiAiAssistantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/register-artisan' | '/api/ai-assistant'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/register-artisan' | '/api/ai-assistant'
  id: '__root__' | '/' | '/auth' | '/register-artisan' | '/api/ai-assistant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  RegisterArtisanRoute: typeof RegisterArtisanRoute
  ApiAiAssistantRoute: typeof ApiAiAssistantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-artisan': {
      id: '/register-artisan'
      path: '/register-artisan'
      fullPath: '/register-artisan'
      preLoaderRoute: typeof RegisterArtisanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-assistant': {
      id: '/api/ai-assistant'
      path: '/api/ai-assistant'
      fullPath: '/api/ai-assistant'
      preLoaderRoute: typeof ApiAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  RegisterArtisanRoute: RegisterArtisanRoute,
  ApiAiAssistantRoute: ApiAiAssistantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
